travis:
  secure:
    BINSTAR_TOKEN: byZlwRkY55nGiGqZyLSmnsUsDoHUP/WjIe3lNu4pzYWQ3yrVdQ644VLNSzKWI0/9SDfkuhRQKEE60MVT6XdLziReuqsjFQtIuhsJgZv6q17r6mR3+4aGJ39MhuHQ/JlyVQ/psRPAvNrZx/4f9xYkaEr9BItpMoR9y8pN4ACO7tXA3pBeiauSzp0NpnOJfddDwLs/sKRtcbTtDQ9aS//xOlJPsqEChbKswdvm92koLQos79yaI2ftA4AMbUK/NVHCjt5bRCBMCAUrFHR+NlpCB5fC/nOS8ylBs5V2Xy3QGIIsfNRDmTg7y8N+vdx3nDKYdu0+ulYFst/09/5b/iclnaAudsNvmz3cOShxsr5eH3UWZG9XxQvpr/2S1qYt/d8KbyJSxSl5LONS5GJTW+v/aPcDthkK/J4vVx6YqUUVLxg44PEHy8P4xahtr8GIlrKN4Ln4QUqPDxKZHapfNDAY4l87+MtlVc7/j6miWfYFRfbL6ISZBC7XOXwcbhbk5NePuCIX2u9lK2Axtb779HqUZAmLXII2wOVGicXp0IpVlAss619/EfQEbm3Drc5lO4rZEehbPlf7TeYPZzsrNUvBwULxL06+dND8vc4H1OyjzCaBc675NMtqXYB+aYi8hWnGLGblHq2DAROPEEm/wGiihMP6ipLrzekNsJH6jCuCaxU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
