travis:
  secure:
    BINSTAR_TOKEN: kf+0hE3YYQUJeQLDULMzj29S6Tetv+V5TJ/M2g4O7Zfwa4+gItJUeh6e3ciD/tGac3rdxNAfGvSn/fdJMtsxFyUN+Y0F1NoHDc5BCgT6jtGCK5/cu/w3dMdo28FjdvHcoiTo7fPClbFtvfSCuMv5Ljmb/uhK+8cIla2uH8WYpPAj9CTGNj8RcHjHNAxUykytCCkveOeSVDtQRa/xN/BTEPtqGDiFd7SPAcO4Uhzkf9LHNs7U0F8jTPJu7/RCTnwi6duKDYbx7oyTxCL4E2o2KZqR73nycwNlEwbFlapTyAQ0/xdVEsn1uziGKmNxopA9N2qIil0I2CYlHeVXm+X8qWCj7mjGRSYEjo5RUPM4x29FnGKw88Zqd2jW6JDpGRF51zS10qsRByKWwh5TzOpPmt3pPFc6SdIeRM8FRCMXUQfsFaMcLvBfntY3YxTEU2+KJrQ3XaseGYT7rEvELGGEaOTvH3ruvFrrGXynnlDL7Y9p+LbK/fQg80VvH/GgUEeET2Y7tHaW0N9UcTgXJQ6tB62fZMl50tEdmlYCoBTRt280CdLXkx0veaJxwH4Ad+JJEzQy8D52+jFFkNm8GpdUB/MsBqt3LjkLBUI23kC9A4LjVcVVtXSs3xOV9pTGMpzq6L+NqhIei8+f0aZ8vIo98BAistoFmvMJGcIsOqditdc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
